version: '3'
services:
   assembler:
    image: shuimengzhi/assembler_environment:1.0
    container_name: assembler
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - ../:/project
    security_opt:
     - seccomp:unconfined
    cap_add:
     - SYS_PTRACE

